services:
  headscale:
    image: docker.io/headscale/headscale:stable
    restart: unless-stopped
    container_name: headscale
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:9090:9090"
    volumes:
      - ~/headscale/config:/etc/headscale
      - ~/headscale/lib:/var/lib/headscale
      - ~/headscale/run:/var/run/headscale
    command: serve
